apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: default
  name: pv-mysql
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /var/lib/mysql
    server: 192.168.175.5

