apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-master
spec:
  replicas: 2
  selector:
    name: redis-master
  template:
    metadata:
      name: redis-master
      labels:
        name: redis-master
    spec:
      containers:
      - name: redis-master
        image: hikubernetes/redis-master:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
